# Copyright 2017 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
---
- name: Install and config mysql
  hosts: mysql
  become: yes
  tasks:
    - name: Install software-properties-common
      package: name=software-properties-common

    - name: Add apt-key for Mariadb packages
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: '0xF1656F24C74CD1D8'

    - name: Add MariaDB repository
      apt_repository:
        repo: deb [arch=amd64,i386] http://mirrors.tuna.tsinghua.edu.cn/mariadb/repo/10.2/ubuntu xenial main

    - name: Install mysql packages
      apt:
        name: ['mariadb-server', 'mariadb-client', 'python-pymysql', 'libmysqlclient-dev']
        install_recommends: yes
        state: latest
        update_cache: yes

    - pip: name=pymysql executable=pip3
    - pip: name=MySQL-python executable=pip

    - name: Copy mysql_secure_installation.sql into place.
      become: yes
      copy:
        src: "{{ labkeeper_config_git_dest }}/zuul/mysql_secure_installation.sql"
        dest: /tmp/mysql_secure_installation.sql
        mode: 0400

    - mysql_db:
        state: import
        name: all
        target: /tmp/mysql_secure_installation.sql

    - mysql_user:
        name: zuul
        host: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
        state: present
        priv: 'zuul.*:ALL'

- name: Config replication mysql service
  hosts: mysql-master, mysql-slave
  become: yes
  tasks:
    - name: Copy my.cnf into place.
      template:
        src: "{{ labkeeper_config_git_dest }}/mysql/my.cnf.j2"
        dest: /etc/mysql/my.cnf

    - name: Restart Mysql servers in master node.
      service:
        name: mysql
        state: restarted

- name: Config replication users
  hosts: mysql-master, mysql-slave
  become: yes
  tasks:
    - name: Ensure replication user exists.
      mysql_user:
        name: "replica"
        host: "{{ item }}"
        password: "replica"
        priv: "*.*:REPLICATION SLAVE,REPLICATION CLIENT"
        state: present
      with_items:
        - localhost
        - "{{ hostvars[groups['mysql-slave'][0]].ansible_host }}"
        - "{{ hostvars[groups['mysql-master'][0]].ansible_host }}"

    - name: Stop slave if already started.
      mysql_replication: mode=stopslave

- name: Config Mysql Slave of replication
  hosts: mysql-slave
  become: yes
  tasks:
    - name: Check slave replication status.
      mysql_replication:
        mode: getslave
        login_user: "replica"
        login_password: "replica"
      ignore_errors: true
      register: slave_status

    - name: Check master replication status.
      mysql_replication:
        mode: getmaster
        login_user: "replica"
        login_password: "replica"
      delegate_to: "{{ groups['mysql-master'][0] }}"
      register: master_status

    - name: Configure replication on the slave.
      mysql_replication:
        mode: changemaster
        master_host: "{{ hostvars[groups['mysql-master'][0]].ansible_host }}"
        master_user: "replica"
        master_password: "replica"
        master_log_file: "{{ master_status.File }}"
        master_log_pos: "{{ master_status.Position }}"
      when:
        - (slave_status.Is_Slave is defined and not slave_status.Is_Slave) or
          (slave_status.Is_Slave is not defined and slave_status is failed)

    - name: Start replication.
      mysql_replication:
        mode: startslave
      when:
      - (slave_status.Is_Slave is defined and not slave_status.Is_Slave) or
        (slave_status.Is_Slave is not defined and slave_status is failed)
